apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: cluster-issuer-cert-manager
message: A clusterwide CA has been established for this project. It will handle the protocol(s) "${AMQ_PROTOCOL}". The username/password for accessing the service is ${AMQ_USER}/${AMQ_PASSWORD}. Please be sure to create a secret named "${AMQ_SECRET}" containing the trust store and key store files ("${AMQ_TRUSTSTORE}" and "${AMQ_KEYSTORE}") used for serving secure content.
metadata:
  annotations:
    description: Template for clusterwide CA. This template supports the issuing of certificates across cluster namespaces.
    openshift.io/display-name: Cluster Wide CA Issuer (Persistence, clustered, with SSL)
    tags: cert-manager
  name: cluster-issuer-cert-manager
objects:
- apiVersion: certmanager.k8s.io/v1alpha1
  kind: Issuer
  metadata:
    name: self-signer
  spec:
    selfSigned: {}
- apiVersion: certmanager.k8s.io/v1alpha1
  kind: Certificate
  metadata:
    name: rootca
  spec:
    secretName: rootca
    issuerRef:
      name: self-signer
    commonName: "ca.self-signer.cert-manager"
    isCA: true
- apiVersion: certmanager.k8s.io/v1alpha1
  kind: ClusterIssuer
  metadata:
    name: ${CERT_ISSUER}
  spec:
    ca:
      secretName: rootca
parameters:
- description: Cert Issuer
  displayName: Cert Issuer
  name: CERT_ISSUER
  required: true
  value: internalpki